- name: httpd 설정
  hosts: all
  become: yes
  vars_files:
    - vars.yml 

  tasks:
    - name: 포트 변경
      lineinfile:
        dest: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        line: "Listen {{ webport }}"
     notify: Restart httpd

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
